version: "3"
networks:
  app-net:
services:
  postgres:
    container_name: cocktailcoach-postgres
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: cocktailcoach
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - app-net
  meili:
    container_name: cocktailcoach-meili
    image: getmeili/meilisearch
    restart: always
    volumes:
      - meili-data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILIKEY}
    ports:
      - 7700:7700
    networks:
      - app-net
  app:
    container_name: cocktailcoach
    build: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - app-net
volumes:
  postgres-data: {}
  meili-data: {}
