version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: cocktailcoach
      POSTGRES_DB: db
    ports:
      - 5432:5432
  meili:
    container_name: meili
    image: getmeili/meilisearch
    restart: always
    volumes:
      - meili-data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILIKEY}
    ports:
      - 7700:7700

volumes:
  postgres-data: {}
  meili-data: {}

