version: '3'

services:
  relational:
    image: postgres
    restart: always
    volumes:
      - /home/admin/db/dump:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432